### ISSUE TITLE
Check `state` parameter during authentication as per Shopify docs.

### ISSUE THREAD

**Issue by gavinballard** [discolabs/django-shopify-auth#17]

**Comment by j0hnsmith** [comment]
How about putting the name of the shop in a [JWT token](https://pyjwt.readthedocs.org/en/latest/usage.html)

    nonce = jwt.encode({
        'shop': shop,
        'exp': now() + timedelta(minutes=1),
    }, settings.SECRET_KEY).decode()

(decode is for python 3+), then checking it in the callback, something like

    try:
        decoded_data = jwt.decode(params['state'], settings.SECRET_KEY)
    except jwt.ExpiredSignatureError:
        return HttpResponse('Please try again', status=status.HTTP_401_UNAUTHORIZED)
    except jwt.InvalidTokenError:
        return HttpResponse('Token error', status=status.HTTP_401_UNAUTHORIZED)

    if decoded_data['shop'] != params['shop']:
        return HttpResponse('Invalid shop', status=status.HTTP_401_UNAUTHORIZED)

The main benefit of using a JWT token is that you don't have to store anything in the db.

**Comment by coler-j** [comment]
Why was this closed? You still don't seem to be using 'state'.
