### ISSUE TITLE
Making API requests without request.user

### ISSUE THREAD

**Issue by andresdouglas** [discolabs/django-shopify-auth#20]
I'm trying to figure out how I would make API requests if the request didn't originate from an authenticated user (when receiving a webhook, for example). I've looked at shopify-sync and shopify-webhook and couldn't find anything to that regard.

**Comment by gavinballard** [comment]
Follow the instructions in [Making API calls](https://github.com/discolabs/django-shopify-auth#7-making-shopify-api-calls), but just use the information provided in the webhook to fetch the appropriate `User` model to call `.session` on.

**Comment by andresdouglas** [comment]
Thanks for the reply. In the webhook, the user_id is "None". Should I be using 'token' to find the user?

**Comment by gavinballard** [comment]
The .myshopify.com domain is passed as a header in the Webhook request, you can use that to look up the appropriate user.



On 29 April 2016 at 6:43:36 PM, Andres Douglas (notifications@github.com) wrote:

Thanks for the reply. In the webhook, the user_id is "None". Should I be using 'token' to find the user?
