### ISSUE TITLE
OperationalError at /login/finalize/ -

### ISSUE THREAD

**Issue by Jinesh510** [discolabs/django-shopify-auth#21]
**Operational error**  
**No such table djangoappname_customuserclass ( the one which inherits AbstractShopUser )**

I followed the instructions as mentioned in readme. The code breaks once i click install app from the developer-store admin page. 

I have made the migrations as well. Is there any update which I am possibly missing ?

**Comment by gavinballard** [comment]
This doesn't sound to me like a problem with the package - seems to be more of an implementation issue with the way you've set up your custom user class. I think you'd be better off providing your code and asking for help in a general-purpose Django forum.

**Comment by Jinesh510** [comment]
Thanks for the reply Gavin. There was some error in the implementation, got it sorted.
