### ISSUE TITLE
NoReverseMatch: Reverse for 'shopify_auth.views.finalize' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

### ISSUE THREAD

**Issue by embedded1** [discolabs/django-shopify-auth#24]
django: 1.10.2
This was sorted just after I added a name property to the finalize URL.

Can you push a fix that includes name for each function?

**Comment by gavinballard** [comment]
@embedded1 Can you please provide exact reproduction steps from a fresh install of Django 1.10? (Or, even better, a test case that exposes the issue)?

**Comment by embedded1** [comment]
It happens when you try to install the app.

Adding view name solved this issue.

**Comment by gavinballard** [comment]
A fix for this has been released in 0.4.7.
