### ISSUE TITLE
Chrome breaking change

### ISSUE THREAD

**Issue by jaydensmith** [discolabs/django-shopify-auth#27]
An email went out to Shopify Partners recently that outlined changes that must be made to Shopify Embedded App OAuth to ensure compatiblity with upcoming releases of Chrome:

https://help.shopify.com/api/sdks/embedded-app-sdk/getting-started#oauth

**Comment by gavinballard** [comment]
@jaydensmith A fix for this has been released in `0.5.0`.

**Comment by coler-j** [comment]
@gavinballard when using your fix do you get a failure in your console:

`ShopifyApp detected that it was not loaded in an iframe and is redirecting to: https://teststorename.myshopify.com/admin/apps/[....some number....]/ app.js:1 F

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://teststorename.myshopify.com') does not match the recipient window's origin ('https://appurl.com').`?

**Comment by gavinballard** [comment]
@coler-j Interesting - I haven't actually tried it going the other way around. I'm afraid we don't actively use this package in production any more so I don't tend to pick up on issues or have time to work on them. I'm more than happy to respond to comments/issues and manage the merging and release of new changes but I can't contribute much code these days.
