### ISSUE TITLE
How do you recommend generating a superuser for admin purposes? 

### ISSUE THREAD

**Issue by yuchant** [discolabs/django-shopify-auth#4]

**Comment by gavinballard** [comment]
Good question! I have been thinking about a potential redesign of the authentication here to avoid having to subclass `AbstractBaseUser` and simply storing Shopify Authentication credentials in a separate database table (much like a user profile pattern). That way people are free to use whatever user model they like and can keep regular patterns and auth measures like password authentication for special users.

For now, you could simply try adding a superuser flag to your user model and manually setting it at the database level for a particular shop to give them access. Obviously that would require the super admin to have the application installed in their shop though.

The ghetto solution would be to provide some views that didn't go through the existing `login_required` decorator but did require Basic HTTP(S) auth.

**Comment by yuchant** [comment]
Hey Gavin, thanks for the thoughtful response!

Understood. I suppose I will always have a test shop that I can make the superuser to use the admin easily. 

Hey I think that rebuild would be great!  How much time do you think that would take? I would definitely support a project like this in time and gifts :+1:

**Comment by gavinballard** [comment]
Oooh, gifts! :).

I don't think it would actually take that long, it's a question of finding the time to do it + test it properly. I'll keep it on the todo list though!

**Comment by gavinballard** [comment]
Closing as I don't have time to work on this. Happy to review and accept PRs though.

**Comment by davis** [comment]
could you describe the changes that would be required for this? I could then try tackling them. I guess one thing would be to have ShopUser extend models.Model with User being a 1 to 1 field... but what else?

**Comment by gavinballard** [comment]
Thanks @davis! I think that would be a good start... the thing is, I'd want to see a compelling use case for why you would want to be writing an app that didn't have the user model correspond 1:1 with a `User`. What's your use case?

**Comment by embedded1** [comment]
Any updates?
This is a must-have-feature.

thanks

**Comment by gavinballard** [comment]
@embedded1 As per above, I don't have time to work on this but will happily review PRs or suggested approaches for the README. If this is must-have, you can set up an external auth mechanism for a superadmin as described above.

**Comment by embedded1** [comment]
Could you explain how to set up the superuser?
Anyone else here got it working? mind sharing how?

Thanks

**Comment by aatishnn** [comment]
Although not sure if this is a good way, I was able to use admin interface in Django 1.11.4 with the following changes:

1. Merge pull requests: #23 and #36  
1. Add is_superuser to user model, add `is_staff`, `has_perm` and `has_module_perms` to make it working with Django admin.
2. Override `ShopUserManager`'s `create_superuser` method so that it sets `is_superuser` and also saves a usable password.

**models.py**
```python
from django.db import models
from shopify_auth.models import AbstractShopUser, ShopUserManager


class SuperShopUserManager(ShopUserManager):
    def create_superuser(self, myshopify_domain, password):
        user = super(SuperShopUserManager, self).create_superuser(
            myshopify_domain, password)
        user.is_superuser = True
        user.set_password(password)
        user.save(using=self._db)


class AuthAppShopUser(AbstractShopUser):
    is_superuser = models.BooleanField(default=False)
    objects = SuperShopUserManager()

    @property
    def is_staff(self):
        return self.is_superuser

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return self.is_superuser
```

3. Add a new backend that accepts username+password and only lets users log in if `SHOPIFY_APP_DEV_MODE` is True.

**backends.py**
```python
from django.contrib.auth.backends import RemoteUserBackend
from django.conf import settings
from django.contrib.auth.hashers import check_password


class SuperShopBackend(RemoteUserBackend):

    def authenticate(self, request, username=None, password=None, **kwargs):
        if not settings.SHOPIFY_APP_DEV_MODE:
            return

        if not username or not password:
            return

        user = super(SuperShopBackend, self).authenticate(request, remote_user=username)
        if user and user.check_password(password):
            return user
        return
```
4. Use this backend together with `shopify_auth`'s backend.
```python
AUTHENTICATION_BACKENDS = [
    'shopify_auth.backends.ShopUserBackend',
    'shop_auth.backends.SuperShopBackend',
]
```
5. Creating superuser with `./manage.py createsuperuser` and logging in with the provided domain+password should work now.

@gavinballard Is this a good way to go?

**Comment by gavinballard** [comment]
Hey @aatishnn, this looks really solid and thanks so much for sharing in detail!

These compatibility issues with more recent versions of Django do seem to crop up pretty often, it's just unfortunate that as I don't use Django any more I can't provide much of an intelligent response on these changes/fixes. As I've said in other PRs, I am super happy to review and merge PRs as long as they contain detailed descriptions of problems and their solutions, and include tests that cover the changes in behaviour.

**Comment by aatishnn** [comment]
@gavinballard Totally understandable scenario of yours. I will try writing tests for these changes and will come up with a PR.
