### ISSUE TITLE
Five Minute Screencast Videos Not Available

### ISSUE THREAD

**Issue by banagale** [discolabs/django-shopify-auth#49]
The embedded videos on your [intro blog entry](http://gavinballard.com/shopify-app-in-15-minutes-with-django/) appear to have the wrong permissions set.
<img width="762" alt="screen shot 2019-01-16 at 8 20 49 am" src="https://user-images.githubusercontent.com/1409710/51262676-b45f9680-1967-11e9-9a30-85ecd508ff28.png">

**Comment by jsartre** [comment]
Hi. Also have a problem on my end getting to the videos. Any chance you could put them back up?
Thx!
Jo
![image](https://user-images.githubusercontent.com/95833/57988125-55667700-7a58-11e9-923f-4f968e51e93e.png)

@banagale @gavinballard @Benoss

**Comment by Benoss** [comment]
looks like @gavinballard video hosting platform is down :(

**Comment by gavinballard** [comment]
Thanks @banagale, @jsartre and @Benoss.

Unfortunately, the screencast service I was using (Quickcast) disappeared without too much notice and I haven’t been able to recover the casts, despite trying. I should really update the page to note this! 

They are quite out of date now in any case though.

Sorry about that!
