### ISSUE TITLE
Django 3 changes

### ISSUE THREAD

**Issue by pbhowmic** [discolabs/django-shopify-auth#54]
The documentation says `SESSION_COOKIE_SAMESITE = False` for Django >=2.1
This needs to be changed to `SESSION_COOKIE_SAMESITE = 'Lax'` for Django>=3.0

**Comment by boolangery** [comment]
Maybe its the same issue but in some browser I'm stuck in a redirection loop

**Comment by stlk** [comment]
Fixed by https://github.com/discolabs/django-shopify-auth/commit/304beb65a2aec56a8048c0125f636b771f7d26a4
