### ISSUE TITLE
request.user is incorrect when using several shop on same client browser

### ISSUE THREAD

**Issue by boolangery** [discolabs/django-shopify-auth#56]
When using several shop in the same browser, request.user is set incorrectly (cookie is the same).
I will try to look at this bug, this is because the app use session auth I think. We need to user hmac auth.

**Comment by boolangery** [comment]
Look at [https://github.com/Shopify/quilt/blob/master/packages/koa-shopify-auth/src/verify-request/login-again-if-different-shop.ts](url)

```
if (session && query.shop && session.shop !== query.shop) {
      clearSession(ctx);
      redirectToAuth(routes, ctx);
      return;
    }
```

I'll try to fix this

**Comment by stlk** [comment]
Fixed in https://github.com/discolabs/django-shopify-auth/commit/726e33882f4a4543caf7633ae3ef7774957ef8da. More info in https://github.com/discolabs/django-shopify-auth/pull/57#issuecomment-739477550
