### ISSUE TITLE
How to avoid redirects out of the Shopify Admin in embedded apps?

### ISSUE THREAD

**Issue by slado122** [discolabs/django-shopify-auth#59]
So, when we finish the stage "Checking cookies", we get redirected to our application page NOT inside an iframe. Is there a way to not leave the Shopify Admin and be fully embedded?

`# Shopify App Setup`
`App URL: https://myapp.com/`
`Whitelisted Redirect URL(s): https://myapp.com/shopify/finalize/`

`# setttings.py`
`LOGIN_URL = '/shopify/login/'`
`LOGIN_REDIRECT_URL = '/'`

`shopify_auth.views` are default.

**Comment by stlk** [comment]
I'm afraid the only way to avoid redirects out of the Shopify Admin is the [token based cookieless auth](https://shopify.dev/tutorials/authenticate-your-app-using-session-tokens). We already migrated one of our apps to this. I hope to write an article about it in following weeks.

**Comment by shashitechno** [comment]
@stlk any documentation on cookieless auth ?

**Comment by stlk** [comment]
@shashitechno yeah, https://github.com/discolabs/django-shopify-auth#embedded-vs-standalone-apps
