### ISSUE TITLE
AttributeError at /  'QueryDict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by tha-friend** [discolabs/django-shopify-auth#6]
Hi again, this is Naveen who shot you an email earlier. I am now getting an error "AttributeError at /
'QueryDict' object has no attribute 'iteritems'" ... probably also related to me using python 3.x.
this line in decorators.py.

47.         shopify_params = dict([(k, v) for k, v in request.GET.iteritems() if k in ['shop', 'timestamp', 'signature', 'hmac']])

**Comment by gavinballard** [comment]
Hey @tha-friend, thanks for the report. I just pushed v0.4.2 of the package that should resolve this specific issue.

Sorry for this piecemeal approach to ensuring Python 3 support, I don't have time right now to set up a proper test for the package, but I'll try to do that soon. In the meantime, feel free to report these issues and I'll fix them up ASAP.

Thanks!
