### ISSUE TITLE
Data too long for column 'token' at row 1

### ISSUE THREAD

**Issue by omerbsh** [discolabs/django-shopify-auth#60]
Hi,
I'm getting this error after installing app:
`django.db.utils.DataError: (1406, "Data too long for column 'token' at row 1")`

seems that the token have some prefix:
`shpat_036ca812b82d3ff34f68a3e9159*****`

* I'm using the latest API version 10_2020 
** when I'm changing the table column _auth_app_authappshopuser.token_ itself to 38 chars the process went smoothly.

**Comment by stlk** [comment]
Fixed by https://github.com/discolabs/django-shopify-auth/commit/e39f1f661ae82d5be3d70376188016e3783a2818
