### ISSUE TITLE
Package doesn't handle reinstalling the app correctly

### ISSUE THREAD

**Issue by nkbelow** [discolabs/django-shopify-auth#61]
In order to get past the Shopify approval process your app must be able to be deleted -> reinstalled. This package doesn't handle this correctly and instead upon reinstall just sends you to a screen that shows invalid and invalid url.

It looks to be an issue with having an expired Django session? I noticed that if I clear out my Django sessions table and then reinstall the app loads fine. I noticed a similar issue with the Koa shopify package here https://github.com/Shopify/quilt/pull/844/files

**Comment by stlk** [comment]
Hi Nicholas, I added mixin that solves this issue https://github.com/discolabs/django-shopify-auth/commit/726e33882f4a4543caf7633ae3ef7774957ef8da

**Comment by nkbelow** [comment]
@stlk Thank you so much! I currently have a workaround in my app to fix this, but am excited to bump the version and remove my fix. Very happy to see that this is still being developed!
