### ISSUE TITLE
no migrations?

### ISSUE THREAD

**Issue by danielmcquillen** [discolabs/django-shopify-auth#7]
Thanks Gavin for this really great library and the accompanying guide/videos . I'm trying to follow along but in Django 8. When I try to run migrations I get

ValueError: Dependency on app with no migrations: my_app

Any thoughts on steps needed to prepare the 'my_app' in your example for migrations?

**Comment by gavinballard** [comment]
Thanks Daniel! I haven't tried this library out with Django 1.8 I'm afraid (all of my stuff is still using 1.7 and in one sad case 1.3).

I'll probably do a pass at 1.8 and 1.9 compatibility when 1.9 is released in December as I don't have a lot of time to allocate to this right now.

In the meantime, if you do find a workaround for this issue please post it here and let me know. It does seem like to sort of thing that should be able to be overridden with a flag in the call to `migrate.py`.

**Comment by danielmcquillen** [comment]
Hmm. Not sure if this completely resolves the issue, but I ran a 

./manage.py makemigrations my_app

And then the migrations, which gave me the cryptic message:

```
Migrations for 'my_app':
  0001_initial.py:
    - Create model MyAppShopUser
(productdiagrams)> ./manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: staticfiles, shopify_auth, messages
  Apply all migrations: admin, my_app, contenttypes, auth, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying my_app.0001_initial... OK
The following content types are stale and need to be deleted:

    auth | user

Any objects related to these content types by a foreign key will also
be deleted. Are you sure you want to delete these content types?
If you're unsure, answer 'no'.

    Type 'yes' to continue, or 'no' to cancel: yes
```
but seemed to work!

**Comment by gavinballard** [comment]
Thanks Daniel! That will have to do for the moment :).

**Comment by danielmcquillen** [comment]
Thanks Gavin. Great stuff!
