### ISSUE TITLE
Webhook installation signal

### ISSUE THREAD

**Issue by cornmander** [discolabs/django-shopify-auth#8]
Hi, can I extend `views.finalize` to emit a Django signal `shopify_auth.signals.shop_registered`? I want to key off that signal in my app so that I can register webhooks into a user's application.

Wanted to run the idea past you to see if you have input on another way of doing this as I want to get this feature merged in :smile:

**Comment by cornmander** [comment]
See #9 .

**Comment by gavinballard** [comment]
Hi @cornmander, thanks for taking the time to try out the package and to offer this contribution! Really appreciate it.

I don't think this PR makes sense for this package, as I want to keep it as simple and minimalistic as possible. There's also an [existing signal](https://docs.djangoproject.com/en/1.8/ref/contrib/auth/#module-django.contrib.auth.signals) built into the Django auth framework (`user_logged_in`) that I think you could use for this specific use case.

If you need this specific signal triggering here for your app, I'd suggest overriding the `finalize` method from within your app - but I think you'll actually be able to get the same result listening to the `user_logged_in` signal.

Thanks again for taking the time to contribute.
