### ISSUE TITLE
document.body is null causing errors

### ISSUE THREAD

**Issue by trev0r** [discolabs/django-shopify-auth#87]
https://github.com/discolabs/django-shopify-auth/blob/b4fb316192de20f11f97a7cc3586858f88f4e95d/shopify_auth/templates/shopify_auth/iframe_redirect.html#L9

This was causing errors for my app because of document.body being null. 

It looks like shopifyData it's not being used. Can this line be removed?

**Comment by stlk** [comment]
Hi Trevor,
thanks for pointing out the unused line. I copied it from Shopify example and forgot to remove it. Feel free to remove it from your code, I'll release this change in the next release. In the meantime you can fix the error by adding `<body>` tag to your HTML.

**Comment by trev0r** [comment]
Appreciate the quick fix and thanks for continuing to maintain this!
